### ISSUE TITLE
Permissions tab never loads

### ISSUE THREAD

**Issue by kai4785** [macdja38/pvpcraft#63]
When I have navigated through the servers page to the server I want to configure, the Permissions tab never loads. Eventually it sends me to an authorization page with a "give me administrator" permissions dialog, which I grant. But then the page reloads back to the page as if I just logged in. Going back to the Permissions page again repeats the cycle.

I am a brand new user, trying to use the application for the first time. The only thing I can think of that I did on my part was to uncheck many of the permissions boxes the first time I attempted an invite. But those seem to be preserved in the roles, and I have done what I could think of to reset it. I've tried kicking the bot, removing the role, removing the application authorization I granted it the first time. The permissions page doesn't seem to load for me at all.

**Comment by macdja38** [comment]
Yea, This is an issue with the way the website connects to the bot to pull data from it, sometimes the bot shards are down / undiscoverable. I'll look at improving the discovery. Thanks for the report.

**Comment by macdja38** [comment]
Happy to be able to say this is probably fixed https://github.com/macdja38/pvpapi/commit/fe24873c004768daf9760f2989ec2f79c20e01cf

The issue was that when a bot shard dropped a connection to the api service the site and bot use the db query that piped configs into the bot wasn't closed, it was still listening to changes for that bot shard's config. Basically the connection pool ended up with 1000 subscriptions, hit a default cap and stopped allowing the bot to connect. This is now fixed as on disconnecting the db query is closed.

**Comment by kai4785** [comment]
Yes, I can confirm it's fixed for me. Thanks for the quick response!
